settings:
  default_control_channel_size: 100
  default_pdata_channel_size: 100

nodes:
  receiver:
    kind: receiver
    plugin_urn: "urn:otel:otap:fake_data_generator"
    out_ports:
      out_port:
        destinations:
          - debug
        dispatch_strategy: round_robin
    config:
      traffic_config:
        max_signal_count: 1000
        max_batch_size: 1000
        signals_per_second: 1000
        log_weight: 100
      registry_path: https://github.com/open-telemetry/semantic-conventions.git[model]

  debug1:
    kind: processor
    plugin_urn: "urn:otel:debug:processor"
    out_ports:
      out_port:
        destinations:
          - attr
        dispatch_strategy: round_robin
    config:
      verbosity: detailed

  attr:
    kind: processor
    plugin_urn: "urn:otap:processor:attributes_processor"
    out_ports:
      out_port:
        destinations:
          - debug2
        dispatch_strategy: round_robin
    config:
      actions:
        - action: "rename"
          source_key: "name"
          destination_key: "name2"
          apply_to: ["scope"]

  debug2:
    kind: processor
    plugin_urn: "urn:otel:debug:processor"
    out_ports:
      out_port:
        destinations:
          - exporter
        dispatch_strategy: round_robin
    config:
      verbosity: detailed


  exporter:
    kind: exporter
    plugin_urn: "urn:otel:noop:exporter"
    config:
