receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otelarrow:
    endpoint: '{{backend_hostname}}:1235'
    compression: none
    arrow:
      payload_compression: zstd
    tls:
      insecure: true

processors:
  transform:
    error_mode: ignore
    trace_statements:
      - set(spanevent.attributes["ios.app.state"], spanevent.attributes["ios.app.state2"])
      - delete_key(spanevent.attributes, "ios.app.state")

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8086
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform]
      exporters: [otelarrow]
