receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  otlp:
    endpoint: '{{backend_hostname}}:1235'
    tls:
      insecure: true

processors:
  transform:
    error_mode: ignore
    trace_statements:
      - set(scope.attributes["name"], scope.attributes["name2"])
      - delete_key(scope.attributes, "name")

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8086
  pipelines:
    logs:
      receivers: [otlp]
      processors: [transform]
      exporters: [otlp]
